apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-productos

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api-productos

  template:
    metadata:
      labels:
        app: api-productos

    spec:
      containers:
      - name: api-productos
        image: allang1/api-productos:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        env:
        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: api-productos-config
              key: APP_VERSION

        - name: APP_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: api-productos-config
              key: APP_ENVIRONMENT