apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-productos

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api-productos

  template:
    metadata:
      labels:
        app: api-productos

    spec:
      containers:
      - name: api-productos
        image: allang1/api-productos:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        env:
        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: api-productos-config
              key: APP_VERSION

        - name: APP_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: api-productos-config
              key: APP_ENVIRONMENT

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: api-productos-secret
              key: DB_USER

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-productos-secret
              key: DB_PASSWORD

        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: api-productos-secret
              key: API_KEY

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5